export default {
    products:[{
        _id: '1',
        name: 'Cape May IPA',
        category:'IPA',
        image: '/images/CapeMayIPA.jpg',
        price: 12,
        brand: 'Cape May Brewery',
        rating: 5.0,
        numReviews: 10,
        countInStock: 0,
    },
    {
        _id:'2',
        name: 'White Caps',
        category: 'IPA',
        image: '/images/Whitecaps.jpg',
        price: 10,
        brand: 'Cape May Brewery',
        rating: 3.5,
        numReviews: 10,
        countInStock: 10,
    },
    {
        _id: '3',
        name: 'Coastal Evacuation',
        category: 'IPA',
        image: '/images/CoastalEvacuation.jpg',
        price: 16,
        brand: 'Cape May Brewery',
        rating: 4.5,
        numReviews: 10,
        countInStock: 8,
    },
    {
        _id: '4',
        name: 'Bounding Man',
        category: 'IPA',
        image: '/images/BoundingMan.jpg',
        price: 14,
        brand: 'Cape May Brewery',
        rating: 4.5,
        numReviews: 10,
        countInStock: 5,
    },
]
}